title: "Madhushan Ramalingam"
short_name: Madhushan
description: "Madhushan Ramalingam is a professional Computer Science researcher in AI/ML with interests in scalable learning systems."
baseurl: ""
url: "https://drmadhushan.github.io/"
email: "drmadhushan@gmail.com"
profile_img: "/assets/img/profile_latest.png"
writeup_message: "This is a structured way of thinking out loud that helps me solidify concepts after reading or learning. Hope it helps you too!"
# writeup_message: "This is a structured louder thinking which help me solidify concepts after I read or learn. Hope this helps you too!"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}

permalink: pretty

collections:
  research:
    output: true
    permalink: /projects/:name/
  publications:
    output: true
    permalink: /publications/:name/
  blogs:
    output: true
    permalink: /blogs/:name/

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: research
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: blog
  - scope:
      path: ""
    values:
      layout: page

sass:
  sass_dir: assets/css
  style: compressed

plugins: []

theme_color: "#12486B"
accent_color: "#E8F1F8"
secondary_color: "#0F3057"
font_serif: "'Source Serif 4', 'Georgia', serif"
font_sans: "'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif"

social:
  scholar: "https://scholar.google.com/citations?user=ooGmN3kAAAAJ&hl=en"
  github: "https://github.com/DrMadhushan"
  linkedin: "https://linkedin.com/in/madhushan-ramalingam/"
  cv: "/assets/docs/cv_latest.pdf"
