### Site Settings ###
title: â²˜â²â²‡â²ðŒµð›“â²â²â²›
head: â²˜â²â²‡â²ðŒµð›“â²â²â²› êž„â²â²™â²ð“µâ²“â²›ð“°â²â²™
description: >
  Learn, Apply, Fail, Fix, Improvise <br>
  Life in an agile cycle!
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: drmadhushan.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/** # For Documentation Only

### Author Info ###
author:
  name: Madhushan
  image: /assets/profile.png
  about-image: /assets/about-image.png
  resume: /public/docs/resume_madhushan.pdf
  # behance: drmadhushan
  # dribbble          : your_username
  email: drmadhushan@gmail.com
  linkedin: madhushan-ramalingam
  github: DrMadhushan
  hackerrank: drmadhushan
  university: e17/194
  facebook: drmadhushan
  # gitlab            : your_username
  instagram: drdhushan
  # kaggle            : your_username
  medium: drmadhushan
  research-gate: Madhushan-Ramalingam-2
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  twitter: drmadhushan
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus:
  shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: dhushan
  color: "#ffe100"
  message: "Lots of love for visiting." # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope: # For Documentation Only
      path: "" # For Documentation Only
      type: "elements" # For Documentation Only
    values: # For Documentation Only
      layout: "element" # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
